apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  namespace: application
spec:
  replicas: 3
  selector:
    matchLabels:
      app: employees
  template:
    metadata:
      labels:
        app: employees
    spec:
      containers:
      - name: web
        image: 917376227412.dkr.ecr.us-east-1.amazonaws.com/myapp:latest
        ports:
        - containerPort: 8080
        env:
        - name: DBHOST
          value: mysql-service.mysql.svc.cluster.local  # points to MySQL service
        - name: DBPORT
          value: "3306"
        - name: DATABASE
          value: employees
        - name: DBUSER
          value: root
        - name: DBPWD
          value: password
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
      imagePullSecrets:
        - name: ecr-secret